Handle nil name in BatchInvitationUser#strip_whitespace_from_name
This was causing a migration [1] to fail in integration with:

    NoMethodError: undefined method `strip!' for nil:NilClass

This makes sense from the point of view that there is no validation on
BatchInvitationUser#name and so there's nothing forcing it to be
present.

I've added a unit test to force me to fix the problem.

[1]: https://github.com/alphagov/signon/blob/afe562d1905c90def59e80a5e483375538fa0935/db/migrate/20230925093143_strip_whitespace_from_batch_invitation_user_organisation_slug.rb