Fix NoMethodError in SessionsController#log_event
Trello: https://trello.com/c/qo01Wq1w

We were seeing the following exception [1] when there was no `user`
param in the request:

    NoMethodError: undefined method `[]' for nil:NilClass (NoMethodError)

I've added a test to demonstrate the problem and fixed it by
using `Devise::SessionsController#sign_in_params` [2].

Since `SessionsController` inherits from `Devise::SessionsController`,
we probably should have been using anyway to properly sanitize the
params. Using that method also has the benefit of fixing the problem,
because it will always return an empty `Hash` rather than `nil`.

[1]: https://govuk.sentry.io/issues/4838149311/?project=202251
[2]: https://www.rubydoc.info/github/plataformatec/devise/Devise%2FSessionsController:sign_in_params