Enabled new Rails 6.1 defaults that don't fail the tests
The remaining ones cause issues, generally because of 'Undefined
method' errors, e.g.

```
NoMethodError: undefined method `active_storage' for #<Rails::Application::Configuration:0x000056499b909fa8>
```

These configurations aren't relevant to Signon, and will be
deleted in the next commit.