Use newer shoulda-context
Locally I run into the following error when running the test suite as
documented in an issue:
https://github.com/thoughtbot/shoulda-context/issues/109

```
undefined local variable or method 'executable' for an instance of Rails::TestUnitReporter (NameError)
```

This is a release candidate, which I'd normally be wary of using, but
it's a test dependency set to `required: false` and the gem appears to
be unmaintained (no commits since August 2024 and official support is
for Rails is two major versions behind), so I think it's worth the bump
to get things working. We use the gem quite heavily in our test suite so
we're unlikely to be able to migrate away without dedicated work